# 头部菜单，title: link
menu:
  个人简介: /other
  Github: https://github.com/lidakai
  Twitter: https://twitter.com/likai_Yu
  分类: /categories
  归档: /archives
  标签云: /tags

# 是否显示目录
TOC: false

# 是否自动播放音乐
autoplay: false

# 默认音乐
mp3: 
  - http://link.hhtjim.com/163/5146554.mp3
  - http://link.hhtjim.com/qq/001faIUs4M2zna.mp3

# 首页封面图, 为空时取文章的cover作为封面
welcome_cover: # /img/welcome-cover.jpg

# 默认文章封面图
cover: /img/cover.jpg

# 是否关闭默认滚动条
scrollbar: true

# Gitalk 评论插件（https://github.com/gitalk/gitalk）
gitalk:
    # 是否自动展开评论框
    autoExpand: false
    # 应用编号
    clientID: 'e41bd515bc03a5ec0ec3'
    # 应用秘钥
    clientSecret: '68b50c6a7e4c93885500d137628cc4656ca6e2fc'
    # issue仓库名
    repo: '七月'
    # Github名
    owner: 'lidakai'
    # Github名
    admin: ['lidakai']
    # Ensure uniqueness and length less than 50
    id: location.pathname
    # Facebook-like distraction free mode
    distractionFreeMode: false

# 网站关键字
keywords: 前端技术、CSS、html、javascript、node、爬虫、后端、个人博客

# 要使用google_analytics进行统计的话，这里需要配置ID
google_analytics: 

# 网站ico
favicon: /img/favicon.ico

# rss文件
rss: atom.xml
